name: Transifex

on:
  push:
    branches:
      - main

jobs:
  push-transifex:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: install transifex
        run: npm install -g @transifex/cli

      - name: Push transifex
        working-directory: client
        env:
          TRANSIFEX_TOKEN: ${{ secrets.TRANSIFEX_TOKEN }}
          TRANSIFEX_SECRET: ${{ secrets.TRANSIFEX_SECRET }}
        run: |
          TRANSIFEX_TOKEN=$TRANSIFEX_TOKEN
          TRANSIFEX_SECRET=$TRANSIFEX_SECRET 
          npx txjs-cli push src/translation/en.json --parser=i18next
