name: Transifex

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  push-transifex:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Change directory
        run: cd client

      - name: Push transifex
        run: |
          TRANSIFEX_TOKEN=${{ secrets.TRANSIFEX_TOKEN }} 
          TRANSIFEX_SECRET=${{ secrets.TRANSIFEX_SECRET }} 
          npx txjs-cli push src/translation/en.json --parser=i18next
