name: Transifex

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  push-transifex:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Push source file using transifex client
        uses: transifex/cli-action@v2
        with:
          token: ${{ secrets.TRANSIFEX_API_TOKEN }}
